"use client";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { Suspense, useEffect, useMemo, useState } from "react";
type Service={id:string;nameAr:string;category:string;subCategory?:string|null;city?:string|null;locationName?:string|null;finalPrice:number;loyaltyPoints:number;images:string[]};
function norm(v?:string|null){return (v||"").trim().toLowerCase()}
function matchesType(s:Service,type:string){const h=norm(s.category+" "+(s.subCategory||""));if(type==="domestic")return h.includes("محلية")||h.includes("داخلي");if(type==="international")return h.includes("عالمية")||h.includes("دولي");if(type==="cruise")return h.includes("كروز")||h.includes("cruise");if(type==="experiences")return !h.includes("برامج سياحية")&&!h.includes("كروز");return true}
const labels:Record<string,string>={domestic:"برامج سياحية محلية",international:"برامج سياحية عالمية",cruise:"رحلات الكروز",experiences:"التجارب"};
export default function Page(){return <Suspense fallback={<main className="min-h-screen bg-[#F7F5EF] pt-32"/>}><Content/></Suspense>}
function Content(){const p=useSearchParams(),type=p.get("type")||"all";const [services,setServices]=useState<Service[]>([]),[city,setCity]=useState(""),[loading,setLoading]=useState(true);useEffect(()=>{fetch("/api/services",{cache:"no-store"}).then(r=>r.json()).then(j=>{if(j.success)setServices(j.data||[])}).finally(()=>setLoading(false))},[]);const typed=useMemo(()=>services.filter(s=>matchesType(s,type)),[services,type]);const cities=useMemo(()=>Array.from(new Set(typed.map(s=>s.city).filter(Boolean))) as string[],[typed]);const shown=city?typed.filter(s=>s.city===city):typed;return <main dir="rtl" className="min-h-screen bg-[#F7F5EF] px-5 pb-24 pt-32 text-[#0D3B34] md:px-8"><div className="mx-auto max-w-[1380px]"><p className="text-[9px] font-bold tracking-[.2em] text-[#B99124]">AREES LOOP</p><h1 className="mt-2 text-4xl font-black">{labels[type]||"البرامج والتجارب"}</h1><div className="mt-6 flex flex-wrap gap-2"><button onClick={()=>setCity("")} className={"rounded-full px-5 py-2 text-xs font-bold "+(!city?"bg-[#0D3B34] text-white":"bg-white")}>كل المواقع</button>{cities.map(x=><button key={x} onClick={()=>setCity(x)} className={"rounded-full px-5 py-2 text-xs font-bold "+(city===x?"bg-[#0D3B34] text-white":"bg-white")}>{x}</button>)}</div>{loading?<div className="mt-8 rounded-3xl bg-white p-10 text-center">جاري تحميل البرامج...</div>:shown.length===0?<div className="mt-8 rounded-3xl bg-white p-10 text-center font-bold">لا توجد برامج منشورة في هذا القسم حالياً.</div>:<div className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{shown.map(s=><article key={s.id} className="overflow-hidden rounded-[28px] bg-white"><div className="aspect-[1.8/1] w-full overflow-hidden bg-[#F5EFE2]">{s.images?.[0] ? <img src={s.images[0]} alt={s.nameAr} className="h-full w-full object-contain" /> : <div className="flex h-full items-center justify-center text-xs text-[#0D3B34]/50">لا توجد صورة</div>}</div><div className="p-5"><p className="text-[10px] font-bold text-[#B99124]">{s.category}</p><h2 className="mt-2 text-xl font-black">{s.nameAr}</h2><p className="mt-2 text-xs text-[#0D3B34]/55">{[s.city,s.locationName].filter(Boolean).join(" · ")}</p><div className="mt-4 flex items-center justify-between gap-3"><b>{Number(s.finalPrice).toLocaleString("ar-SA")} ر.س</b><span className="flex items-center gap-2 rounded-full bg-[#D4AF37]/10 px-3 py-2 text-[10px] font-bold text-[#9A741B]"><img src="/Logo/arees-loop-logo.png" className="h-6 w-auto" alt="Arees Loop"/> احجز واحصل على {s.loyaltyPoints||150} نقطة</span></div><Link href={`/services/${s.id}`} className="mt-5 flex justify-center rounded-xl bg-[#0D3B34] py-3 text-xs font-bold text-white">عرض التفاصيل</Link></div></article>)}</div>}</div></main>}
