"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
type Item={serviceId:string;quantity:number};
type Service={id:string;nameAr:string;finalPrice:number;images:string[];loyaltyPoints:number};
const KEY="arees-loop-cart-v1";
export default function CartPage(){
 const [items,setItems]=useState<Item[]>([]),[services,setServices]=useState<Service[]>([]),[loading,setLoading]=useState(true);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(KEY)||"[]");if(Array.isArray(saved))setItems(saved.filter(x=>typeof x.serviceId==="string"&&Number.isInteger(x.quantity)&&x.quantity>0))}catch{}fetch("/api/services",{cache:"no-store"}).then(r=>r.json()).then(d=>{if(d.success)setServices(d.data||[])}).finally(()=>setLoading(false))},[]);
 const save=(next:Item[])=>{setItems(next);localStorage.setItem(KEY,JSON.stringify(next));window.dispatchEvent(new Event("arees-cart-updated"))};
 const rows=items.map(item=>({item,service:services.find(s=>s.id===item.serviceId)}));
 const total=rows.reduce((sum,row)=>sum+(row.service?Number(row.service.finalPrice)*row.item.quantity:0),0);
 return <main dir="rtl" className="min-h-screen bg-[#F7F5EF] px-5 pb-24 pt-32 text-[#0D3B34]"><div className="mx-auto max-w-4xl"><h1 className="text-3xl font-black">سلة حجوزاتك</h1><p className="mt-2 text-sm opacity-70">راجع الخدمات والكميات قبل تأكيد الحجز والدفع.</p>{loading?<p className="mt-8">جارٍ تحميل السلة...</p>:rows.length===0?<div className="mt-8 rounded-3xl bg-white p-8">السلة فارغة حالياً. <Link href="/discover" className="font-bold underline">استكشف البرامج</Link></div>:<><div className="mt-7 space-y-4">{rows.map(({item,service})=><article key={item.serviceId} className="flex flex-wrap items-center gap-4 rounded-2xl bg-white p-4 shadow-sm">{service?.images?.[0]&&<img src={service.images[0]} alt="" className="h-24 w-24 rounded-xl object-contain"/>}<div className="min-w-0 flex-1"><h2 className="font-bold">{service?.nameAr||"خدمة غير متاحة حالياً"}</h2><p className="mt-1 text-sm">{service?Number(service.finalPrice).toLocaleString("ar-SA")+" ر.س":"لا يمكن حساب السعر"}</p></div><div className="flex items-center gap-3"><button aria-label="تقليل الكمية" onClick={()=>save(items.map(x=>x.serviceId===item.serviceId?{...x,quantity:Math.max(1,x.quantity-1)}:x))} className="rounded-lg border px-3 py-2">−</button><b>{item.quantity}</b><button aria-label="زيادة الكمية" onClick={()=>save(items.map(x=>x.serviceId===item.serviceId?{...x,quantity:x.quantity+1}:x))} className="rounded-lg border px-3 py-2">+</button><button onClick={()=>save(items.filter(x=>x.serviceId!==item.serviceId))} className="rounded-lg px-3 py-2 text-red-700">حذف</button></div></article>)}</div><div className="mt-6 rounded-2xl bg-white p-6"><div className="flex justify-between font-bold"><span>الإجمالي المبدئي</span><span>{total.toLocaleString("ar-SA")} ر.س</span></div><p className="mt-3 text-sm opacity-70">الدفع الإلكتروني وتأكيد الحجز غير مفعّلين بعد. لن يُخصم أي مبلغ أو نقاط من حسابك.</p><div className="mt-4 flex flex-wrap gap-2"><span className="rounded-xl border px-4 py-2 text-xs opacity-60">تابي — قريباً</span><span className="rounded-xl border px-4 py-2 text-xs opacity-60">تمارا — قريباً</span><Link href="/discover" className="rounded-xl bg-[#0D3B34] px-4 py-2 text-xs font-bold text-white">إضافة خدمات أخرى</Link></div></div></>}</div></main>
}