import {utcLicenseDay} from "@/lib/license-validity";
import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
export const dynamic = "force-dynamic";
export default async function GuideProfile({params}:{params:Promise<{id:string}>}){
 const {id}=await params;
 const guide=await prisma.partner.findFirst({where:{id,partnerType:"INDIVIDUAL",status:"ACTIVE",licenses:{some:{status:"VERIFIED",expiryDate:{gte:utcLicenseDay()},OR:[{type:{contains:"إرشاد"}},{type:{contains:"GUIDE",mode:"insensitive"}}]}}},select:{publicName:true,legalNameAr:true,descriptionAr:true,city:true,locationName:true,logoUrl:true,licenses:{where:{status:"VERIFIED",expiryDate:{gte:utcLicenseDay()}},select:{type:true,issuer:true,licenseNumber:true,expiryDate:true}}}});
 if(!guide)notFound();
 return <main dir="rtl" className="min-h-screen bg-[#F8F5ED] px-5 pb-24 pt-36 text-[#0D3B34]"><div className="mx-auto max-w-4xl"><Link href="/guides" className="text-sm font-bold text-[#A87917]">← جميع المرشدين</Link><div className="mt-5 overflow-hidden rounded-3xl border border-[#D4AF37]/30 bg-white shadow-lg"><div className="flex flex-col gap-7 p-7 md:flex-row"><div className="flex h-64 w-full shrink-0 items-center justify-center overflow-hidden rounded-2xl bg-[#F2EDE2] md:w-64">{guide.logoUrl?<img src={guide.logoUrl} alt={guide.publicName||guide.legalNameAr} className="h-full w-full object-contain"/>:<span className="text-6xl text-[#0D3B34]/25">◉</span>}</div><div><p className="font-bold text-[#A87917]">مرشد سياحي معتمد</p><h1 className="mt-2 text-3xl font-black">{guide.publicName||guide.legalNameAr}</h1><p className="mt-3 font-bold">📍 {guide.city||guide.locationName||"المملكة العربية السعودية"}</p><p className="mt-5 leading-8 text-[#0D3B34]/70">{guide.descriptionAr||"مرشد سياحي مرخص"}</p><div className="mt-5 space-y-2">{guide.licenses.map(l=><p key={l.licenseNumber} className="rounded-lg bg-[#F8F5ED] p-3 text-sm">{l.type} — {l.issuer} — رقم الترخيص: {l.licenseNumber}</p>)}</div><p className="mt-5 text-sm text-[#0D3B34]/60">الحجز الإلكتروني للمرشدين سيتاح بعد اكتمال ربط الخدمات والمواعيد المعتمدة.</p></div></div></div></div></main>;
}