"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
type Suggestion={id:string;title:string;message:string;href:string;createdAt:string;unread:boolean};
export default function NotificationsPage(){
 const [items,setItems]=useState<Suggestion[]>([]);
 const [loading,setLoading]=useState(true);
 const [error,setError]=useState("");
 useEffect(()=>{fetch("/api/account/interest-suggestions",{cache:"no-store"}).then(async response=>{if(response.status===401){window.location.href="/login";return null;}const data=await response.json();if(!response.ok)throw new Error(data.message||"تعذر تحميل الإشعارات");return data;}).then(data=>{if(data)setItems(data.suggestions||[])}).catch(e=>setError(e instanceof Error?e.message:"تعذر تحميل الإشعارات")).finally(()=>setLoading(false))},[]);
 async function markRead(ids:string[]){if(!ids.length)return;try{const response=await fetch("/api/account/interest-suggestions",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({serviceIds:ids})});if(!response.ok)throw new Error("تعذر تحديث حالة الإشعارات");setItems(previous=>previous.map(item=>ids.includes(item.id)?{...item,unread:false}:item));window.dispatchEvent(new Event("arees:interest-notifications-updated"));}catch(e){setError(e instanceof Error?e.message:"تعذر تحديث الإشعارات")}}
 const unread=items.filter(x=>x.unread);
 return <main dir="rtl" className="mx-auto min-h-screen max-w-4xl px-5 pb-20 pt-36 text-[#0D3B34]"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-black">الإشعارات</h1><p className="mt-3 text-sm">تجارب جديدة تناسب اهتمامات التسجيل والخدمات التي حفظتها بالقلب.</p></div><button disabled={!unread.length} onClick={()=>void markRead(unread.map(x=>x.id))} className="rounded-xl border border-[#D4AF37]/50 bg-white px-4 py-2 text-sm disabled:opacity-40">تعليم الكل كمقروء ({unread.length})</button></div>{loading?<p className="mt-8">جاري تحميل الإشعارات...</p>:<section className="mt-8 space-y-3">{items.map(item=><article key={item.id} className={"rounded-2xl border p-5 "+(item.unread?"border-[#B99124] bg-[#FFF9E9]":"border-[#D4AF37]/20 bg-white")}><Link href={item.href} onClick={()=>void markRead([item.id])} className="block"><p className="font-bold">{item.title} {item.unread&&<span className="mr-2 text-xs text-[#B99124]">جديد</span>}</p><p className="mt-2 text-sm">{item.message}</p><time className="mt-3 block text-xs opacity-60">{new Date(item.createdAt).toLocaleDateString("ar-SA")}</time></Link>{item.unread&&<button onClick={()=>void markRead([item.id])} className="mt-3 text-xs underline">تعليم كمقروء</button>}</article>)}{!items.length&&<p className="rounded-2xl bg-white p-6">لا توجد تجارب جديدة مطابقة حالياً. اختر اهتماماتك أو احفظ تجربة بالقلب.</p>}</section>}{error&&<p role="alert" className="mt-4 text-red-700">{error}</p>}<Link href="/interests" className="mt-7 inline-block text-sm font-bold underline">عرض اهتماماتي</Link></main>;
}
