"use client";
import {useEffect,useState} from "react";
type Guide={id:string;fullName:string;email:string;phone:string;countries:string[];city:string;licenseCategory:string;licenseNumber:string;licenseExpiresAt:string;status:string;photoPublicationConsent:boolean;reviewNotes:string|null};
export default function GuideApplicationsAdmin(){
 const [items,setItems]=useState<Guide[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 async function refresh(){try{const r=await fetch("/api/admin/guides",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.message||"غير مصرح");setItems(d.data||[])}catch(e){setError(e instanceof Error?e.message:"تعذر التحميل")}finally{setLoading(false)}}
 useEffect(()=>{void refresh()},[]);
 async function review(id:string,status:"APPROVED"|"REJECTED"|"NEEDS_COMPLETION"){
  const note=window.prompt("سجل نتيجة فحص الترخيص وملاحظات القرار (20 حرفاً على الأقل):");
  if(!note||note.trim().length<20)return;
  const confirmed=status==="APPROVED"?window.confirm("هل فحصت المستند وتحققت من رقم الترخيص وفئته وصلاحيته لدى الجهة المختصة؟"):false;
  if(status==="APPROVED"&&!confirmed)return;
  try{const r=await fetch("/api/admin/guides",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status,reviewNotes:note,confirmLicenseVerified:confirmed})});const d=await r.json();if(!r.ok)throw new Error(d.message||"تعذر تحديث الطلب");await refresh()}catch(e){setError(e instanceof Error?e.message:"تعذر تحديث الطلب")}
 }
 return <main dir="rtl" className="min-h-screen bg-[#F8F5ED] px-5 pb-20 pt-32 text-[#0D3B34]"><div className="mx-auto max-w-6xl"><h1 className="text-3xl font-black">مراجعة طلبات المرشدين</h1><p className="mt-3 text-sm">الاعتماد يتطلب فحص الترخيص ومطابقته لدى الجهة المختصة وتسجيل دليل المراجعة. لا تُعرض وثائق المرشد للعامة.</p>{loading?<p className="mt-8">جاري التحميل...</p>:<div className="mt-8 grid gap-4">{items.map(g=><article key={g.id} className="rounded-2xl bg-white p-5"><h2 className="text-lg font-bold">{g.fullName}</h2><p className="text-sm">{g.email} · {g.phone}</p><p className="mt-2 text-sm">{g.licenseCategory} — {g.licenseNumber} — {new Date(g.licenseExpiresAt).toLocaleDateString("ar-SA")}</p><p className="mt-1 text-sm">{g.city} · {g.countries.join("، ")}</p><p className="mt-1 text-xs">نشر الصورة: {g.photoPublicationConsent?"موافق":"غير موافق"} · الحالة: {g.status}</p><div className="mt-3 flex gap-3 text-sm"><a target="_blank" rel="noopener noreferrer" className="underline" href={`/api/admin/guides/document?id=${encodeURIComponent(g.id)}&kind=license`}>عرض الترخيص</a><a target="_blank" rel="noopener noreferrer" className="underline" href={`/api/admin/guides/document?id=${encodeURIComponent(g.id)}&kind=photo`}>عرض الصورة</a></div>{g.status==="UNDER_REVIEW"&&<div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>void review(g.id,"APPROVED")} className="rounded-xl bg-[#0D3B34] px-4 py-2 text-sm text-white">اعتماد بعد التحقق</button><button onClick={()=>void review(g.id,"NEEDS_COMPLETION")} className="rounded-xl bg-amber-100 px-4 py-2 text-sm">طلب استكمال</button><button onClick={()=>void review(g.id,"REJECTED")} className="rounded-xl bg-red-50 px-4 py-2 text-sm text-red-700">رفض</button></div>}{g.reviewNotes&&<p className="mt-3 text-xs">ملاحظات المراجعة: {g.reviewNotes}</p>}</article>)}</div>}{error&&<p role="alert" className="mt-5 text-red-700">{error}</p>}</div></main>;
}
