"use client";
import ServiceHistory from "./ServiceHistory";
import TeamRoleHistory from "./TeamRoleHistory";
import {useEffect,useMemo,useState} from "react";
type Kind="dashboard"|"bookings"|"settlements"|"invoices"|"reports"|"team"|"business";
const titles={dashboard:"الرئيسية",bookings:"الحجوزات",settlements:"التسويات",invoices:"الفواتير",reports:"التقارير",team:"الموظفون والصلاحيات",business:"المنشأة والتراخيص"};
const money=(v:any)=>new Intl.NumberFormat("ar-SA",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0));
const date=(v:any)=>v?new Date(v).toLocaleDateString("ar-SA"):"—";
export default function PartnerDataPage({kind}:{kind:Kind}){
 const [d,setD]=useState<any>(null);const [error,setError]=useState("");
 useEffect(()=>{fetch("/api/partner/portal",{credentials:"include",cache:"no-store"}).then(r=>r.json()).then(x=>x.success?setD(x):setError(x.message||"تعذر تحميل البيانات")).catch(()=>setError("تعذر تحميل البيانات"));},[]);
 const [bookingQuery,setBookingQuery]=useState("");
 const [bookingStatus,setBookingStatus]=useState("ALL");
 const [teamBusy,setTeamBusy]=useState<string|null>(null);
 const [teamMessage,setTeamMessage]=useState("");
 const [teamHistoryRefresh,setTeamHistoryRefresh]=useState(0);
 const updateTeamRole=async(memberId:string,role:"MANAGER"|"EMPLOYEE")=>{
  if(!window.confirm("تأكيد تغيير دور الموظف؟"))return;
  setTeamBusy(memberId);setTeamMessage("");
  try{
   const response=await fetch("/api/partner/team",{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({memberId,role})});
   const result=await response.json();
   if(!response.ok||!result.success)throw new Error(result.message||"تعذر تعديل الدور");
   const refreshed=await fetch("/api/partner/portal",{credentials:"include",cache:"no-store"}).then(r=>r.json());
   if(!refreshed.success)throw new Error("تم الحفظ، لكن تعذر تحديث القائمة.");
   setD(refreshed);setTeamHistoryRefresh(x=>x+1);setTeamMessage("تم تحديث دور الموظف.");
  }catch(e){setTeamMessage(e instanceof Error?e.message:"تعذر تعديل الدور");}
  finally{setTeamBusy(null);}
 };
 const stats=useMemo(()=>{if(!d)return null;const sales=d.bookings.reduce((a:number,b:any)=>a+Number(b.totalAmount||0),0);return{sales,bookings:d.bookings.length,services:d.services.length,settlements:d.settlements.reduce((a:number,s:any)=>a+Number(s.netAmount||0),0)}},[d]);
 if(error)return <main className="p-8"><div className="rounded-3xl bg-white p-8 text-red-700">{error}</div></main>;
 if(!d)return <main className="p-8">جاري تحميل بيانات الشريك...</main>;
 const access=d.access;
 if((kind==="bookings"&&!access?.bookings?.view)||(kind==="team"&&!access?.team?.view)||((kind==="settlements"||kind==="invoices")&&!access?.finances?.view))return <main dir="rtl" className="p-8 text-[#0D3B34]"><h1 className="text-2xl font-bold">{titles[kind]}</h1><p className="mt-4 rounded-2xl bg-white p-6">ليس لديك صلاحية الاطلاع على هذا القسم.</p></main>;
 const empty=(s:string)=><div className="rounded-3xl border border-dashed border-[#0D3B34]/20 bg-white p-10 text-center text-sm text-[#0D3B34]/55">لا توجد {s} حالياً</div>;
 const table=(heads:string[],rows:any[][])=><div className="overflow-x-auto rounded-3xl bg-white"><table className="w-full text-sm"><thead className="bg-[#0D3B34] text-white"><tr>{heads.map(h=><th key={h} className="p-4 text-right">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="border-b border-black/5">{r.map((x,j)=><td key={j} className="p-4">{x??"—"}</td>)}</tr>)}</tbody></table></div>;
 return <main dir="rtl" className="min-h-screen bg-[#F7F4EA] p-5 text-[#0D3B34] md:p-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold text-[#B99124]">AREES LOOP PARTNER</p><h1 className="mt-2 text-3xl font-bold">{titles[kind]}</h1><p className="mt-1 text-sm opacity-60">{d.partner?.tradeNameAr||d.partner?.legalNameAr||"حساب الشريك"} — بيانات فعلية من حساب المنشأة</p>
 {kind==="dashboard"&&<><div className="my-7 grid gap-4 md:grid-cols-4">{[["إجمالي الحجوزات",access?.bookings?.view?stats?.bookings:"غير مصرح"],["الخدمات",stats?.services],["قيمة الحجوزات",access?.finances?.view?money(stats?.sales)+" ر.س":"غير مصرح"],["صافي التسويات",access?.finances?.view?money(stats?.settlements)+" ر.س":"غير مصرح"]].map(x=><div key={x[0] as string} className="rounded-3xl bg-white p-5"><p className="text-xs opacity-55">{x[0]}</p><b className="mt-2 block text-2xl">{x[1]}</b></div>)}</div>{access?.bookings?.view&&d.bookings.length?table(["الحجز","العميل","الخدمة","الإجمالي","الحالة"],d.bookings.slice(0,8).map((b:any)=>[b.reference,b.customerName,b.service?.nameAr,access?.finances?.view?money(b.totalAmount)+" ر.س":"غير مصرح",b.status])):empty("حجوزات")}</>}
 {kind==="bookings"&&<section className="mt-7 space-y-5"><div className="flex flex-wrap gap-3 rounded-3xl bg-white p-4"><input aria-label="البحث في الحجوزات" className="min-w-52 flex-1 rounded-xl border border-black/10 p-3 text-sm" placeholder="ابحث برقم الحجز أو العميل أو الخدمة" value={bookingQuery} onChange={e=>setBookingQuery(e.target.value)}/><select aria-label="تصفية حالة الحجز" className="rounded-xl border border-black/10 p-3 text-sm" value={bookingStatus} onChange={e=>setBookingStatus(e.target.value)}><option value="ALL">جميع الحالات</option>{Array.from(new Set(d.bookings.map((b:any)=>String(b.status)))).map((s:any)=><option key={s} value={s}>{s}</option>)}</select></div>{(()=>{const q=bookingQuery.trim().toLocaleLowerCase();const filtered=d.bookings.filter((b:any)=>(bookingStatus==="ALL"||b.status===bookingStatus)&&(!q||[b.reference,b.customerName,b.service?.nameAr].some(v=>String(v||"").toLocaleLowerCase().includes(q))));return filtered.length?table(["الحجز","العميل","الخدمة","عدد الأشخاص","تاريخ الخدمة","الإجمالي","الحالة"],filtered.map((b:any)=>[b.reference,b.customerName,b.service?.nameAr,b.guests,date(b.serviceDate),access?.finances?.view?money(b.totalAmount)+" ر.س":"غير مصرح",b.status])):empty("حجوزات مطابقة للبحث")})()}</section>}
 {kind==="settlements"&&(d.settlements.length?table(["رقم التسوية","الفترة","المبيعات","عمولة المنصة","الاستردادات","الصافي","الحالة"],d.settlements.map((s:any)=>[s.settlementNumber,date(s.periodStart)+" - "+date(s.periodEnd),money(s.grossSales),money(s.platformCommission),money(s.refunds),money(s.netAmount),s.status])):empty("تسويات"))}
 {kind==="invoices"&&(d.invoices.length?table(["الفاتورة","الحجز","العميل","الخدمة","الإجمالي","الحالة"],d.invoices.map((i:any)=>[i.invoiceNumber,i.booking?.reference,i.booking?.customerName,i.booking?.service?.nameAr,money(i.totalAmount)+" ر.س",i.status])):empty("فواتير"))}
 {kind==="reports"&&<div className="my-7 grid gap-4 md:grid-cols-4">{[["الحجوزات",access?.bookings?.view?stats?.bookings:"غير مصرح"],["الخدمات",stats?.services],["إجمالي المبيعات",access?.finances?.view?money(stats?.sales)+" ر.س":"غير مصرح"],["صافي التسويات",access?.finances?.view?money(stats?.settlements)+" ر.س":"غير مصرح"]].map(x=><div key={x[0] as string} className="rounded-3xl bg-white p-6"><p className="text-xs opacity-55">{x[0]}</p><b className="mt-2 block text-2xl">{x[1]}</b></div>)}</div>}
 {kind==="team"&&<section className="mt-7 space-y-4">{teamMessage&&<p role="status" className="rounded-xl bg-white p-4">{teamMessage}</p>}{d.members.length?<div className="overflow-x-auto rounded-3xl bg-white"><table className="w-full text-sm"><thead className="bg-[#0D3B34] text-white"><tr>{["المستخدم","البريد","الجوال","المسمى","الدور","الحالة","الإجراء"].map(h=><th key={h} className="p-4 text-right">{h}</th>)}</tr></thead><tbody>{d.members.map((m:any)=>{const role=m.permissions?.role||"LEGACY";const editable=d.access?.team?.manage&&m.isActive&&(role==="EMPLOYEE"||(role==="MANAGER"&&d.access?.role==="OWNER"))&&m.userId!==d.access?.userId;return <tr key={m.id} className="border-b border-black/5"><td className="p-4">{[m.user?.firstName,m.user?.lastName].filter(Boolean).join(" ")||"—"}</td><td className="p-4">{m.user?.email||"—"}</td><td className="p-4">{m.user?.phone||"—"}</td><td className="p-4">{m.jobTitle||"—"}</td><td className="p-4">{({OWNER:"مالك",MANAGER:"مدير",EMPLOYEE:"موظف",LEGACY:"غير مصنف"} as Record<string,string>)[role]||"غير مصنف"}</td><td className="p-4">{m.isActive?"نشط":"غير نشط"}</td><td className="p-4">{editable?<select aria-label="تعديل دور الموظف" disabled={teamBusy===m.id} value={role} onChange={e=>updateTeamRole(m.id,e.target.value as "MANAGER"|"EMPLOYEE")} className="rounded-lg border p-2"><option value="EMPLOYEE">موظف</option>{d.access?.role==="OWNER"&&<option value="MANAGER">مدير</option>}</select>:<span className="opacity-60">محمي</span>}</td></tr>})}</tbody></table></div>:empty("موظفين")}</section>}
 {kind==="team"&&d.access?.team?.manage&&<TeamRoleHistory members={d.members} refreshKey={teamHistoryRefresh}/>}
 {kind==="team"&&<ServiceHistory/>}
 {kind==="business"&&<><div className="my-7 grid gap-4 md:grid-cols-2"><div className="rounded-3xl bg-white p-6"><h2 className="font-bold">بيانات المنشأة</h2><div className="mt-4 space-y-3 text-sm"><p>الاسم: <b>{d.partner?.legalNameAr||"—"}</b></p><p>الاسم التجاري: <b>{d.partner?.tradeNameAr||"—"}</b></p><p>الرقم الموحد: <b>{d.partner?.unifiedNumber||"—"}</b></p><p>السجل التجاري: <b>{d.partner?.commercialRegister||"—"}</b></p><p>الرقم الضريبي: <b>{d.partner?.vatNumber||"—"}</b></p><p>المدينة: <b>{d.partner?.city||"—"}</b></p></div></div><div className="rounded-3xl bg-white p-6"><h2 className="font-bold">الحساب والتواصل</h2><div className="mt-4 space-y-3 text-sm"><p>البريد: <b>{d.partner?.businessEmail||"—"}</b></p><p>الجوال: <b>{d.partner?.businessPhone||"—"}</b></p><p>البنك: <b>{d.partner?.bankName||"—"}</b></p><p>IBAN: <b>{d.partner?.iban||"—"}</b></p></div></div></div>{d.licenses.length?table(["الترخيص","الجهة","الرقم","الانتهاء","الحالة"],d.licenses.map((l:any)=>[l.type,l.issuer,l.licenseNumber,date(l.expiryDate),l.status])):empty("تراخيص")}</>}
 </div></main>
}