"use client";
import {useEffect,useState} from "react";
type RecordItem={id:string;action:string;createdAt:string;serviceName:string;employee:string;beforeData?:{nameAr?:string;status?:string;finalPrice?:string};afterData?:{nameAr?:string;status?:string;finalPrice?:string}};
const names:Record<string,string>={PARTNER_SERVICE_CREATED:"إضافة خدمة",PARTNER_SERVICE_UPDATED:"تعديل خدمة",PARTNER_SERVICE_HIDDEN:"إخفاء خدمة",PARTNER_SERVICE_REPUBLISHED:"إعادة نشر",PARTNER_SERVICE_DELETED:"حذف خدمة"};
export default function ServiceHistory(){
 const [items,setItems]=useState<RecordItem[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 useEffect(()=>{fetch("/api/partner/service-history",{cache:"no-store"}).then(r=>r.json()).then(d=>{if(d.success)setItems(d.data||[]);else setError(d.message||"تعذر تحميل السجل")}).catch(()=>setError("تعذر تحميل السجل")).finally(()=>setLoading(false))},[]);
 return <section dir="rtl" className="mt-8 rounded-3xl bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">سجل نشاط الموظفين والخدمات</h2><p className="mt-2 text-sm opacity-60">من أضاف الخدمة ومن عدّلها، مع تاريخ ووقت العملية. يسجل النظام العمليات الجديدة من تاريخ تفعيل السجل.</p>{loading?<p className="mt-5 text-sm">جارٍ تحميل السجل...</p>:error?<p className="mt-5 text-sm text-red-700">{error}</p>:items.length===0?<p className="mt-5 text-sm">لا توجد عمليات مسجلة بعد.</p>:<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[650px] text-right text-sm"><thead><tr className="border-b bg-[#F7F5EF]"><th className="p-3">الخدمة</th><th className="p-3">العملية</th><th className="p-3">الموظف</th><th className="p-3">التاريخ والوقت</th><th className="p-3">التغيير</th></tr></thead><tbody>{items.map(x=><tr key={x.id} className="border-b"><td className="p-3 font-semibold">{x.serviceName}</td><td className="p-3">{names[x.action]||x.action}</td><td className="p-3">{x.employee}</td><td className="p-3">{new Date(x.createdAt).toLocaleString("ar-SA",{timeZone:"Asia/Riyadh"})}</td><td className="p-3 text-xs">{x.beforeData?.nameAr!==x.afterData?.nameAr&&x.afterData?.nameAr?"تغيير الاسم: "+x.afterData.nameAr:x.beforeData?.status!==x.afterData?.status&&x.afterData?.status?"الحالة: "+x.afterData.status:x.beforeData?.finalPrice!==x.afterData?.finalPrice&&x.afterData?.finalPrice?"السعر: "+x.afterData.finalPrice:"—"}</td></tr>)}</tbody></table></div>}</section>;
}
