"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
type Favorite={id:string;nameAr:string;category:string;city:string|null;country:string|null;finalPrice:number;images:string[]};
export default function Page(){
 const [items,setItems]=useState<Favorite[]>([]);
 const [interests,setInterests]=useState<string[]>([]);
 const [loading,setLoading]=useState(true);
 const [error,setError]=useState("");
 useEffect(()=>{fetch("/api/account/interests",{cache:"no-store"}).then(async r=>{if(r.status===401){window.location.href="/login";return null;}const data=await r.json();if(!r.ok)throw new Error(data.message||"تعذر تحميل الاهتمامات");return data;}).then(data=>{if(data){setItems(data.services||[]);setInterests(data.interests||[]);}}).catch(e=>setError(e instanceof Error?e.message:"تعذر تحميل الاهتمامات")).finally(()=>setLoading(false));},[]);
 async function remove(id:string){try{const r=await fetch("/api/account/interests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({serviceId:id,liked:false})});if(!r.ok)throw new Error("تعذر إزالة الخدمة");setItems(previous=>previous.filter(x=>x.id!==id));}catch(e){setError(e instanceof Error?e.message:"تعذر التحديث");}}
 return <main dir="rtl" className="mx-auto min-h-screen max-w-5xl px-5 pb-20 pt-36 text-[#0D3B34]"><h1 className="text-3xl font-black">اهتماماتي</h1><p className="mt-3 text-sm">اهتماماتك من التسجيل، والخدمات التي حفظتها بالقلب.</p>{loading?<p className="mt-8">جاري التحميل...</p>:<><section className="mt-8 rounded-2xl bg-white p-6"><h2 className="font-bold">اهتماماتي الأساسية</h2><div className="mt-3 flex flex-wrap gap-2">{interests.length?interests.map(x=><span key={x} className="rounded-full bg-[#F5EFE2] px-4 py-2 text-sm">{x}</span>):<p className="text-sm">لم تحدد اهتمامات عند التسجيل.</p>}</div></section><h2 className="mt-8 text-xl font-bold">الخدمات المفضلة</h2><div className="mt-4 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{items.map(item=><article key={item.id} className="overflow-hidden rounded-2xl bg-white shadow-sm">{item.images[0]&&<img src={item.images[0]} alt={item.nameAr} className="h-44 w-full object-cover"/>}<div className="p-5"><p className="text-xs text-[#B99124]">{item.category}</p><h3 className="mt-2 font-bold">{item.nameAr}</h3><p className="mt-2 text-sm">{[item.country,item.city].filter(Boolean).join(" · ")}</p><div className="mt-4 flex items-center justify-between"><Link href={`/services/${item.id}`} className="rounded-lg bg-[#0D3B34] px-4 py-2 text-sm text-white">التفاصيل</Link><button onClick={()=>void remove(item.id)} aria-label="إزالة من اهتماماتي" className="text-2xl text-red-600">♥</button></div></div></article>)}</div>{items.length===0&&<p className="mt-4">لم تحفظ أي خدمة بعد. اضغط القلب بجانب أي تجربة تعجبك.</p>}</>}{error&&<p role="alert" className="mt-4 text-red-700">{error}</p>}</main>;
}
