"use client";
import { useEffect,useState } from "react";
const items=[["discover","اكتشف"],["how","كيف تعمل؟"],["programs","برامج سياحية"],["guides","المرشدون السياحيون"],["hotels","الفنادق"],["flights","الطيران"],["cruise","الكروز"],["partners","للشركاء"]] as const;
type Key=typeof items[number][0];
export default function AdminNavigationSettings(){
 const [data,setData]=useState<Record<string,boolean>>({}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{fetch("/api/navigation",{cache:"no-store"}).then(r=>r.json()).then(d=>{if(d.success)setData(d.data);if(d.pendingMigration)setMessage("تنبيه: ترحيل قاعدة البيانات لم يطبق بعد؛ لا يمكن حفظ التغييرات.")}).finally(()=>setLoading(false))},[]);
 async function toggle(key:Key){setBusy(key);setMessage("");try{const response=await fetch("/api/navigation",{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({key,visible:!data[key]})});const result=await response.json();if(!response.ok||!result.success)throw Error(result.message||"فشل الحفظ");setData(d=>({...d,[key]:result.data.visible}));setMessage("تم حفظ الإعداد. قد يحتاج الزائر لتحديث الصفحة لرؤية التغيير.");}catch(e){setMessage(e instanceof Error?e.message:"تعذر الحفظ")}finally{setBusy("")}}
 return <main dir="rtl" className="mx-auto max-w-4xl px-5 py-10 text-[#0D3B34]"><h1 className="text-3xl font-black">إعدادات ظهور روابط الهيدر</h1><p className="mt-3 leading-8 text-[#0D3B34]/70">يمكنك إظهار أو إخفاء روابط القائمة العلوية. إخفاء الرابط لا يحذف الصفحة ولا يمنع الوصول إليها عبر رابط مباشر. الحفظ متاح للمدير العام فقط.</p>{message&&<p role="status" className="my-5 rounded-xl bg-[#FFF5D9] p-4 text-sm">{message}</p>}{loading?<p className="mt-8">جارٍ تحميل الإعدادات…</p>:<div className="mt-8 divide-y divide-[#D4AF37]/20 overflow-hidden rounded-2xl border border-[#D4AF37]/25 bg-white">{items.map(([key,label])=><div key={key} className="flex items-center justify-between gap-4 px-6 py-5"><span className="font-bold">{label}</span><button type="button" disabled={!!busy} aria-pressed={data[key]??true} onClick={()=>toggle(key)} className={`min-w-28 rounded-full px-5 py-2.5 text-sm font-bold transition disabled:opacity-50 ${data[key]===false?"bg-[#E8E8E8] text-[#555]":"bg-[#0D3B34] text-white"}`}>{busy===key?"جارٍ الحفظ…":data[key]===false?"مخفي — إظهار":"ظاهر — إخفاء"}</button></div>)}</div>}</main>;
}
