"use client";
import Link from "next/link";
import {useState,type FormEvent} from "react";
import {GUIDE_LICENSE_CATEGORIES,SAUDI_CITY_SUGGESTIONS} from "@/lib/guides/reference-data";
export default function GuideRegisterPage(){
 const [sending,setSending]=useState(false),[message,setMessage]=useState(""),[success,setSuccess]=useState(false),[gender,setGender]=useState("MALE"),[photoConsent,setPhotoConsent]=useState(false);
 async function submit(event:FormEvent<HTMLFormElement>){
  event.preventDefault();setSending(true);setMessage("");try{
   const data=new FormData(event.currentTarget);
   data.set("gender",gender);data.set("photoPublicationConsent",photoConsent?"yes":"no");
   const response=await fetch("/api/guides/apply",{method:"POST",body:data});
   const result=await response.json();setMessage(result.message||"تعذر إرسال الطلب.");setSuccess(Boolean(result.success));
  }catch{setMessage("تعذر الاتصال بالخدمة. حاول مجدداً.");}finally{setSending(false)}
 }
 const field="w-full rounded-xl border border-[#0D3B34]/20 bg-[#FCFAF5] px-4 py-3 text-sm outline-none focus:border-[#B99124]";
 return <main dir="rtl" className="min-h-screen bg-[#F8F5ED] px-5 pb-24 pt-36 text-[#0D3B34]"><section className="mx-auto max-w-4xl rounded-3xl border border-[#D4AF37]/30 bg-white p-6 shadow-sm md:p-10"><p className="text-xs font-bold tracking-widest text-[#A87917]">AREES LOOP GUIDES</p><h1 className="mt-3 text-3xl font-black">طلب التسجيل كمرشد سياحي</h1><p className="mt-4 text-sm leading-7 opacity-75">أكمل بياناتك وارفع الترخيص الساري. يجب إنشاء حساب وتأكيد البريد الإلكتروني قبل إرسال الطلب. جميع الطلبات تخضع للتدقيق والموافقة قبل نشر أي ملف.</p><div className="mt-4 flex gap-4 text-sm"><Link href="/register" className="underline">إنشاء حساب</Link><Link href="/login" className="underline">تسجيل الدخول</Link></div>
 <div className="mt-8 grid grid-cols-3 gap-2 text-center text-xs font-bold"><span className="rounded-xl bg-[#EAE3D0] p-3">1. البيانات الشخصية</span><span className="rounded-xl bg-[#EAE3D0] p-3">2. الترخيص والتغطية</span><span className="rounded-xl bg-[#EAE3D0] p-3">3. الموافقات والإرسال</span></div>
 <form onSubmit={submit} className="mt-7 space-y-7">
 <fieldset className="grid gap-4 md:grid-cols-2"><legend className="mb-4 text-lg font-black">البيانات الشخصية والتواصل</legend><label className="text-sm font-bold">الاسم الكامل *<input required minLength={4} maxLength={120} name="fullName" className={field}/></label><label className="text-sm font-bold">البريد الإلكتروني المؤكد في حسابك *<input required name="email" type="email" className={field}/></label><label className="text-sm font-bold">رقم الجوال مع مفتاح الدولة *<input required name="phone" type="tel" placeholder="+9665xxxxxxxx" className={field}/></label><label className="text-sm font-bold">الجنس *<select value={gender} onChange={e=>setGender(e.target.value)} className={field}><option value="MALE">ذكر</option><option value="FEMALE">أنثى</option></select></label></fieldset>
 <fieldset className="grid gap-4 md:grid-cols-2"><legend className="mb-4 text-lg font-black">الترخيص ونطاق العمل</legend><label className="text-sm font-bold">فئة الترخيص *<select required name="licenseCategory" className={field}><option value="">اختر الفئة</option>{GUIDE_LICENSE_CATEGORIES.map(c=><option key={c} value={c}>{c}</option>)}</select></label><label className="text-sm font-bold">رقم ترخيص الإرشاد *<input required name="licenseNumber" className={field}/></label><label className="text-sm font-bold">تاريخ انتهاء الترخيص *<input required name="licenseExpiresAt" type="date" className={field}/></label><label className="text-sm font-bold">صورة الترخيص (PDF أو صورة، حتى 5MB) *<input required name="license" type="file" accept=".pdf,image/jpeg,image/png,image/webp" className={field}/></label><label className="text-sm font-bold">مدينة الانطلاق *<input required name="city" list="guide-cities" className={field}/></label><label className="text-sm font-bold">الدول التي تغطيها *<textarea required name="countries" rows={2} placeholder="السعودية، السودان، مصر..." className={field}/></label><label className="text-sm font-bold">اللغات التي تقدم بها الإرشاد *<input required name="languages" placeholder="العربية، الإنجليزية..." className={field}/></label><label className="text-sm font-bold">التخصص أو المسارات<input name="specialization" maxLength={300} className={field}/></label></fieldset>
 <datalist id="guide-cities">{SAUDI_CITY_SUGGESTIONS.map(city=><option key={city} value={city}/>)}</datalist>
 <fieldset className="space-y-4"><legend className="mb-4 text-lg font-black">الصورة الشخصية والموافقة على النشر</legend><label className="block text-sm font-bold">الصورة الشخصية (اختيارية، حتى 5MB)<input name="photo" type="file" accept="image/jpeg,image/png,image/webp" className={field}/></label><label className="flex items-start gap-3 rounded-xl bg-[#F8F5ED] p-4 text-sm"><input type="checkbox" checked={photoConsent} onChange={e=>setPhotoConsent(e.target.checked)} className="mt-1"/><span>أوافق صراحةً على نشر صورتي الشخصية في ملفي العام بعد اعتماد الطلب. يمكنني عدم الموافقة واستخدام الصورة الرمزية بدلاً منها.</span></label><p className="text-sm leading-7 opacity-75">إذا لم توافق على نشر الصورة، ستظهر أيقونة رمزية أبيض وأسود: رجل يرتدي العقال للذكور، أو امرأة محجبة للإناث. لا يُنشر ملفك أو ترخيصك قبل المراجعة.</p><label className="block text-sm font-bold">نبذة عن خبرتك<textarea name="bio" maxLength={2000} rows={4} className={field}/></label></fieldset>
 <label className="flex items-start gap-3 rounded-xl border border-[#D4AF37]/30 p-4 text-sm leading-7"><input required type="checkbox" name="policyAccepted" value="yes" className="mt-2"/><span>أقر بصحة البيانات والتراخيص المقدمة، وأوافق على <Link href="/terms" target="_blank" className="font-bold underline">الشروط والأحكام</Link> و<Link href="/privacy" target="_blank" className="font-bold underline">سياسة الخصوصية</Link> ومعالجة بيانات الطلب لأغراض التحقق والمراجعة. هذه الموافقة مستقلة عن إذن نشر الصورة.</span></label>
 {message&&<p role="status" className={"rounded-xl p-4 text-sm "+(success?"bg-green-50 text-green-800":"bg-red-50 text-red-800")}>{message}</p>}
 <button type="submit" disabled={sending||success} className="w-full rounded-xl bg-[#0D3B34] px-6 py-4 font-bold text-white disabled:opacity-60">{sending?"جاري إرسال الطلب...":"إرسال طلب الانضمام للمراجعة"}</button>
 </form></section></main>;
}
