"use client";
import Image from "next/image";
import Link from "next/link";
import {useParams} from "next/navigation";
import {useEffect,useState} from "react";
type Service={id:string;nameAr:string;nameEn?:string|null;category:string;subCategory?:string|null;descriptionAr?:string|null;city?:string|null;locationName?:string|null;finalPrice:number;capacity?:number|null;cancellationPolicy?:string|null;meetingInstructions?:string|null;partnerName?:string|null;organizerType?:string|null;organizerName?:string|null;organizerLicenseNumber?:string|null;organizerLicenseIssuer?:string|null;images:string[]};
export default function ServiceDetails(){
 const {id}=useParams<{id:string}>(); const [service,setService]=useState<Service|null>(null); const [loading,setLoading]=useState(true); const [qty,setQty]=useState(1); const [imageIndex,setImageIndex]=useState(0);
 useEffect(()=>{fetch("/api/services",{cache:"no-store"}).then(r=>r.json()).then(d=>{if(d?.success)setService((d.data||[]).find((x:Service)=>x.id===id)||null)}).finally(()=>setLoading(false))},[id]);
 if(loading)return <main dir="rtl" className="min-h-screen bg-[#F7F5EF] p-10 text-center text-[#0D3B34]">جارٍ تحميل البرنامج...</main>;
 if(!service)return <main dir="rtl" className="min-h-screen bg-[#F7F5EF] p-10 text-center text-[#0D3B34]"><h1 className="text-2xl font-bold">الخدمة غير متاحة</h1><Link href="/services" className="mt-5 inline-block underline">العودة للخدمات والتجارب</Link></main>;
 const total=Number(service.finalPrice||0)*qty, images=service.images||[];
 const raw=service.descriptionAr||""; const read=(name:string)=>{const m=raw.match(new RegExp(`<div data-arees-section="${name}" style="display:none">([\\s\\S]*?)<\\/div>`));return (m?.[1]||"").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&amp;/g,"&").trim();};
 const includes=read("includes"),excludes=read("excludes"),notes=read("notes"); const hiddenSections=new RegExp('<div data-arees-section="(?:includes|excludes|notes)" style="display:none">[\\\\s\\\\S]*?</div>','g'); const description=raw.replace(hiddenSections,"").trim();
 const lines=(v:string)=>v.split(/\\r?\\n/).map(x=>x.trim()).filter(Boolean);
 const next=()=>setImageIndex(i=>(i+1)%images.length), prev=()=>setImageIndex(i=>(i-1+images.length)%images.length);
 return <main dir="rtl" className="min-h-screen bg-[#F7F5EF] text-[#0D3B34]">
  <header className="border-b border-[#0D3B34]/10 bg-white/75"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><Link href="/"><Image src="/Logo/arees-loop-logo.png" alt="Arees Loop" width={150} height={70} className="h-auto w-[120px]"/></Link><Link href="/services" className="text-xs font-bold">← الخدمات والتجارب</Link></div></header>
  <div className="mx-auto max-w-6xl px-5 py-8">
   <div className="mb-6 text-right"><p className="text-xs font-bold opacity-50">{service.category}{service.subCategory&&` · ${service.subCategory}`}</p><h1 className="mt-2 text-3xl font-bold leading-tight">{service.nameAr}</h1><p className="mt-2 text-sm opacity-55">{service.city}{service.locationName&&` · ${service.locationName}`}</p></div>
   <div className="grid items-start gap-8 lg:grid-cols-[minmax(0,1fr)_minmax(360px,520px)]" dir="ltr">
    <section dir="rtl" className="rounded-[24px] bg-white p-6 shadow-sm md:p-7">
     <h2 className="arees-body flex items-center gap-2 text-xl font-semibold"><span className="flex h-8 w-8 items-center justify-center rounded-xl bg-[#0D3B34] text-white">◆</span> تفاصيل البرنامج</h2>
     <div className="mt-5 text-sm leading-8 text-[#0D3B34]/75 [&_p]:mb-2 [&_ul]:mr-5 [&_ul]:list-disc [&_ol]:mr-5 [&_ol]:list-decimal [&_strong]:font-bold [&_strong]:text-[#0D3B34]" dangerouslySetInnerHTML={{__html:description||"<p>تفاصيل البرنامج قيد الاستكمال.</p>"}}/>
     {includes&&<div className="mt-7"><h3 className="flex items-center gap-2 font-semibold text-[#0D3B34]"><span>●</span> يشمل البرنامج</h3><ul className="mt-2 space-y-1 text-sm leading-7 opacity-70">{lines(includes).map((x,i)=><li key={i}>✓ {x}</li>)}</ul></div>}
     {excludes&&<div className="mt-7"><h3 className="flex items-center gap-2 font-semibold text-[#0D3B34]"><span>◆</span> لا يشمل البرنامج</h3><ul className="mt-2 space-y-1 text-sm leading-7 opacity-70">{lines(excludes).map((x,i)=><li key={i}>• {x}</li>)}</ul></div>}
     {notes&&<div className="mt-7"><h3 className="flex items-center gap-2 font-semibold text-[#0D3B34]"><span>◆</span> ملاحظات مهمة</h3><ul className="mt-2 space-y-1 text-sm leading-7 opacity-70">{lines(notes).map((x,i)=><li key={i}>• {x}</li>)}</ul></div>}
     {service.meetingInstructions&&<div className="mt-7"><h3 className="flex items-center gap-2 font-semibold text-[#0D3B34]"><span>●</span> تعليمات وملاحظات</h3><p className="mt-2 text-sm leading-7 opacity-65">{service.meetingInstructions}</p></div>}
     {service.cancellationPolicy&&<div className="mt-7"><h3 className="flex items-center gap-2 font-semibold text-[#B99124]"><span>◆</span> سياسة الإلغاء والاسترداد</h3><div className="mt-2 text-sm leading-7 opacity-65" dangerouslySetInnerHTML={{__html:service.cancellationPolicy}}/></div>}
     {(service.partnerName||service.organizerName||service.organizerLicenseNumber||service.organizerLicenseIssuer)&&<div className="mt-7 border-t border-[#0D3B34]/10 pt-4"><div className="grid gap-1.5 text-[10px] italic leading-5 text-[#0D3B34]/35 [font-family:Georgia,serif]"><p><span className="font-bold">مقدم الخدمة:</span> {service.partnerName||"—"}</p><p><span className="font-bold">منظم البرنامج:</span> {service.organizerType==="OTHER"?(service.organizerName||"—"):(service.partnerName||"—")}</p>{service.organizerLicenseIssuer&&<p><span className="font-bold">جهة الترخيص أو التصريح:</span> {service.organizerLicenseIssuer}</p>}{service.organizerLicenseNumber&&<p><span className="font-bold">رقم الترخيص/التصريح:</span> {service.organizerLicenseNumber}</p>}</div></div>}
    </section>
    <div dir="rtl" className="lg:sticky lg:top-6">
     <div className="relative mx-auto aspect-square w-full max-w-[520px] overflow-hidden rounded-[24px] border border-[#0D3B34]/8 bg-white shadow-sm">
      {images.length?<img src={images[imageIndex]} alt={service.nameAr} className="h-full w-full object-contain"/>:<div className="flex h-full items-center justify-center text-sm font-bold opacity-35">لا توجد صورة مرفوعة لهذه الخدمة</div>}
      {images.length>1&&<><button onClick={prev} aria-label="الصورة السابقة" className="absolute right-3 top-1/2 flex h-10 w-10 -translate-y-1/2 items-center justify-center rounded-full bg-white/95 text-xl shadow-md">›</button><button onClick={next} aria-label="الصورة التالية" className="absolute left-3 top-1/2 flex h-10 w-10 -translate-y-1/2 items-center justify-center rounded-full bg-white/95 text-xl shadow-md">‹</button><div className="absolute bottom-3 left-1/2 -translate-x-1/2 rounded-full bg-[#0D3B34]/85 px-3 py-1 text-[10px] font-bold text-white">{imageIndex+1} / {images.length}</div></>}
     </div>
     {images.length>1&&<div className="mx-auto mt-2 flex max-w-[520px] justify-center gap-2 overflow-x-auto py-1">{images.map((src,i)=><button key={src+i} onClick={()=>setImageIndex(i)} className={`h-12 w-12 shrink-0 overflow-hidden rounded-lg border-2 ${i===imageIndex?"border-[#B99124]":"border-transparent"}`}><img src={src} alt="" className="h-full w-full object-contain"/></button>)}</div>}
     <aside className="mx-auto mt-4 w-full max-w-[520px] rounded-[24px] border border-[#B99124]/20 bg-white p-5 shadow-sm">
      <div className="flex items-end justify-between gap-4"><div><p className="text-[11px] opacity-50">السعر يبدأ من</p><p className="mt-1 text-2xl font-bold">{Number(service.finalPrice).toLocaleString("ar-SA")} <span className="text-sm">ر.س</span></p></div><div><p className="mb-1 text-[11px] opacity-50">الكمية</p><div className="flex items-center rounded-xl border border-[#0D3B34]/15"><button onClick={()=>setQty(q=>Math.max(1,q-1))} className="h-9 w-9 text-lg">−</button><b className="min-w-9 text-center">{qty}</b><button onClick={()=>setQty(q=>q+1)} className="h-9 w-9 text-lg">+</button></div></div></div>
      <div className="mt-4 flex items-center justify-between border-t border-[#0D3B34]/8 pt-3 text-sm"><span>الإجمالي</span><b>{total.toLocaleString("ar-SA")} ر.س</b></div>
      <div className="mt-4 grid grid-cols-2 gap-2"><button className="flex items-center justify-center gap-2 rounded-xl border border-[#0D3B34] py-3 text-xs font-bold"><span className="text-base">🛒</span> ضع في السلة</button><button className="flex items-center justify-center gap-2 rounded-xl bg-[#0D3B34] py-3 text-xs font-bold text-white"><span>◆</span> احجز الآن</button></div>
      <div className="mt-4 grid gap-2 sm:grid-cols-2"><div className="rounded-xl border border-[#B99124]/20 bg-[#F7F4EA] p-3"><p className="text-[10px] font-bold text-[#B99124]">★ نقاط AREES LOOP</p><p className="mt-1 text-[11px] opacity-60">استخدم نقاطك عند إتمام الحجز</p></div><div className="rounded-xl border border-[#B99124]/35 bg-[#F7F4EA] p-3"><p className="text-[10px] font-bold text-[#B99124]">◆ كوبون خصم</p><div className="mt-2 flex overflow-hidden rounded-lg border border-[#0D3B34]/20 bg-white"><input placeholder="أدخل الكود" className="min-w-0 flex-1 px-2 py-1.5 text-[11px] outline-none"/><button className="border-r border-[#0D3B34]/10 px-2 text-[10px] font-bold">تطبيق</button></div></div></div>
     </aside>
    </div>
   </div>
  </div>
 </main>;
}